# Generated by Django 4.2.3 on 2023-07-17 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0004_remove_city_location_geo_locationcity'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='location_geo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='locat_geo', to='location.locationgeo'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='LocationCity',
        ),
    ]
